### ISSUE TITLE
Failed to execute script

### ISSUE THREAD

**Issue by keerah** [yoursamlan/pubsidian#10]
Hi and thanks for this cool tool
This is my first try of it and I am getting "Failed to execute script PubsidianConverter" error when executing the exe file

**Comment by yoursamlan** [comment]
Hello and Sorry for the inconvenience.

Can you please specify the OS info [Windows 10/11 or lower]?
I have just run it on Windows 11, 21H2 (Build 22000.613) and it works fine.

If you have Python 3.7 or later installed on your PC, please try running the [script](https://github.com/yoursamlan/pubsidian/tree/main/tools/GUI) manually and cite me the error. It will help me understand the problem better.

Thank you for reporting and sorry again for the inconvenience. :(

**Comment by corvusdeinanis** [comment]
Hi! Same problem while running the .exe version (1.0 alpha). Tried running the script manually, installed all the requirements but this is what I get -
` File "C:\yyyyy\xxxx\DashboardPlusPlus-master\PubsidianConverter.py", line 152, in <module>
    eel.start('app.html', size=(800, 800))
  File "C:\Users\yyyyy\AppData\Roaming\Python\Python39\site-packages\eel\__init__.py", line 120, in start
    brw.open(start_urls, options)
  File "C:\Users\yyyyy\AppData\Roaming\Python\Python39\site-packages\eel\browsers.py", line 35, in open
    chm.run(options, start_urls)
  File "C:\Users\yyyyy\AppData\Roaming\Python\Python39\site-packages\eel\chrome.py", line 17, in run
    raise EnvironmentError(
OSError: Can't find Chrome or Chromium installation`


Windows 10, Python 3.9 

In all likelihood, I'm messing up somewhere. 

P.S. - Love your work! And ayy fellow Indian Obsidian user :D

**Comment by yoursamlan** [comment]
Hi, thank you so much and sorry for those errors. Actually the GUI of the program is running on [python-eel](https://github.com/ChrisKnott/Eel), which, by default uses chrome environment/ windows to interact with the user.
According to your log, either you haven't installed the chrome browser on your desktop or the path of chromium (chrome browser) isn't available in the PC for the user. 

This is an [issue](https://github.com/ChrisKnott/Eel/issues/588) of Python-eel. You can bypass the error just by [telling eel to open the GUI on default browser](https://stackoverflow.com/questions/68740121/how-to-start-python-eel-in-any-available-browser-of-user-system). 

Tell me if it fixes the problem or not. If the error still exits, I will roll out a command line tool after the exam (on 21st this month).

Thanks again for pointing out those detailed bugs. :)

**Comment by corvusdeinanis** [comment]
Hi! So that does fix the issue! Editing `eel\__init__.py` and changing the mode works! 

The web app open but for some reason, only the ones without yaml front matter are being processed. But this issue is solved so can mark it solved ig? :D

**Comment by yoursamlan** [comment]
Sorry for replying late. 

As you can see in my script, I am using [python-markdown library](https://pypi.org/project/Markdown) to parse it into HTML with a few tweaks (*like `==` to make `<mark>` the statement etc.*) . Now, as per the project documentation, it strives to follow the [rules mentioned here](https://daringfireball.net/projects/markdown/syntax). And thus, it fails to parse YFM and gives an error. I'm currently working on a new markdown parser, which can understand YFM as well as certain built in variables (like `published`, `tags` etc.) and even with custom title and styling. Will update soon once it's completed. 😅
