### ISSUE TITLE
Linux use AttributeError: module 'eel' has no attribute 'addText'

### ISSUE THREAD

**Issue by darkpandarts** [yoursamlan/pubsidian#12]
Hi. I'm trying to run the tools?GUI code as desribed in this other issue

https://github.com/yoursamlan/pubsidian/issues/3

However, i get the following error

```
Converting -> README.md
module 'eel' has no attribute 'addText'
Converting -> _Index_of_NeuroXpanse.md
module 'eel' has no attribute 'addText'

data.json has been created successfully.
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/home/bsgt/Desktop/pubsidian/venv/lib/python3.8/site-packages/eel/__init__.py", line 207, in _process_message
    return_val = _exposed_functions[message['name']](*message['args'])
  File "GUI/PubsidianConverter.py", line 154, in tf
    convert(name)
  File "GUI/PubsidianConverter.py", line 128, in convert
    createJSON(findex)
  File "GUI/PubsidianConverter.py", line 46, in createJSON
    eel.addText("<b style='color:green;'>data.json has been created successfully.</b>")
AttributeError: module 'eel' has no attribute 'addText'
2022-10-06T11:46:54Z <Greenlet at 0x7f1c726986a0: _process_message({'call': 1.061577083049783, 'name': 'tf', 'args': , <geventwebsocket.websocket.WebSocket object at 0x7)> failed with AttributeError
```

Do you know how i can fix it? I copied/pasted the GUI folder into Obsidian-workspace-root, then ran `python GUI/PubsidianConverter.py`

Also do you have a version of the code without the GUI elements? It would be easier for me to automate without the GUI. 

Many thanks! :)

Best,
nxp

**Comment by yoursamlan** [comment]
Greetings, 
Thanks for using pubsidian. 

This is a limitation of `eel` in Linux. Eel requires `chrome.exe` in windows to execute its GUI interface.  I think you need to configure the same (probably firefox or chromium for Linux) beforehand to implement the GUI.

Coming to your second query. Yes, I have a CLI for the same, but it is depreciated and hasn't been maintained for a long time. However, its core functionality is the same as the GUI one. You can check it out [here](https://github.com/yoursamlan/pubsidian/tree/main/tools/%5BARCHIVED%5D) 

Tell me if it solves your issue, if not, I will create an up-to-date CLI version for cross-platform once I get some free time.

Thanks again for pointing out the issue and also for using pubsidian.

Amlan.
