### ISSUE TITLE
[feature request] select files to publish

### ISSUE THREAD

**Issue by PabloLION** [yoursamlan/pubsidian#4]
I don't know how obsidian publish works but I do know they have an option to select which file to publish.
I think we split this feature to some steps.

1. not export files starting with `_` (or regex `/$_/`)
2. use any regex
3. use a file possibly named `__export_rule__.json` or `.obsidian/__export_rule__.json`
4. offer a GUI to select files. Show the file tree in the output web, use some color to highlight 'exporting files'(saved in `__export_rule__`) and new files, no highlight for 'private files'(will not export, also saved in `__export_rule__`).
5. maybe link this `__export_rule__` file with git to track files. (no idea how to do this)

If you are not working on this, maybe I can try to PR.

**Comment by PabloLION** [comment]
`__export_rule__` in step 3,4,5 can also named as `pubsidian_rule` or anything you want.

**Comment by PabloLION** [comment]
this file can be like `.gitignore`

**Comment by yoursamlan** [comment]
Noted. Will work on that after getting some spare time 😅.

**Comment by PabloLION** [comment]
I used [zoni/obsidian-export](https://github.com/zoni/obsidian-export). I stopped my own repo too.
