### ISSUE TITLE
Make a Mac version?

### ISSUE THREAD

**Issue by padgett1** [yoursamlan/pubsidian#8]
the title says it all - I'm going to try to figure out how to recompile it myself, but in the meantime if you happen to feel like it, I'd appreciate it.

**Comment by padgett1** [comment]
turns out I found a better alternative

**Comment by rohitkrishna094** [comment]
@padgett1 what's the alternative that you found?

**Comment by padgett1** [comment]
@rohitkrishna094 , I found https://github.com/Mara-Li/mkdocs_obsidian_template works like a charm.
